name: CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        cache: false
    - uses: actions/checkout@v4
    - name: Build & Test
      run: |
        go build -v ./...
        go test -coverprofile=c.out -v ./...
        go tool cover -func=c.out
        go tool cover -html=c.out -o coverage.html
    - uses: actions/upload-artifact@v3
      with:
        path: coverage.html

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v --print-resources-usage --enable gofmt

