name: medialib-ci

on:
  push:
    branches: 
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17
      id: go
    - uses: actions/checkout@v3

    - name: Build & Test
      run: |
        go build -v ./...
        go test -v ./...


