name: medialib-ci

on:
  push:
    branches: 
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - uses: actions/checkout@v3
    - name: Build & Test
      run: |
        go build -v ./...
        go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v --print-resources-usage --enable gofmt

