name: Release Go Binaries

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        app: [mediadump, flv2avc, mp42avc]
    steps:
      - uses: actions/checkout@v4
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ./cmd/${{ matrix.app }}
          binary_name: ${{ matrix.app }}
          build_flags: -v -tags ${{ env.APP_VERSION }}
          md5sum: false
